# Generated by Django 3.0.4 on 2020-03-14 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_no', models.CharField(default=0, help_text='Enter house number here.', max_length=10, validators=[django.core.validators.RegexValidator('^[0-99999]*$', message='Only numbers are allowed.')])),
                ('full_name', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z Ññ]*$', message='Only letters are allowed.')])),
                ('last_name', models.CharField(help_text='Enter surname here.', max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z Ññ]*$', message='Only letters are allowed.')])),
                ('first_name', models.CharField(help_text='Enter first name here.', max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z Ññ]*$', message='Only letters are allowed.')])),
                ('middle_name', models.CharField(help_text='Enter middle name here.', max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z Ññ]*$', message='Only letters are allowed.')])),
                ('name_extension', models.CharField(blank=True, choices=[(' JR.', 'Jr.'), (' SR.', 'Sr.'), (' II', 'II'), (' III', 'III')], help_text='Choose name extension, if required.', max_length=4)),
                ('address', models.CharField(help_text='Enter house no. and street no.', max_length=40)),
                ('birth_place', models.CharField(help_text='Enter city of birth only.', max_length=20)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], help_text='Choose gender.', max_length=6)),
                ('civil_status', models.CharField(choices=[('MARRIED', 'MARRIED'), ('SINGLE', 'SINGLE'), ('SEPARATED', 'SEPARATED'), ('WIDOWED', 'WIDOWED')], help_text='Choose civil status.', max_length=10)),
                ('citizenship', models.CharField(choices=[('FILIPINO', 'FILIPINO'), ('FOREIGNER', 'FOREIGNER')], help_text='Choose citizenship.', max_length=10)),
                ('occupation', models.CharField(help_text='Enter occupation here.', max_length=40)),
            ],
        ),
    ]
