# Generated by Django 3.0.4 on 2020-11-05 05:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='CivilStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_status', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('household_no', models.SmallIntegerField(help_text='Enter household number here.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a name for the household.', max_length=50)),
                ('address', models.CharField(help_text='Enter house no. and street no.', max_length=100)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NameExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_extension', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=240, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z Ññ ,]*$', message='Only letters are allowed.')])),
                ('last_name', models.CharField(help_text='Enter surname here.', max_length=128, validators=[django.core.validators.RegexValidator('^[a-zA-Z Ññ]*$', message='Only letters are allowed.')])),
                ('first_name', models.CharField(help_text='Enter first name here.', max_length=128, validators=[django.core.validators.RegexValidator('^[a-zA-Z Ññ]*$', message='Only letters are allowed.')])),
                ('middle_name', models.CharField(blank=True, help_text='Enter middle name here, if needed.', max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z Ññ]*$', message='Only letters are allowed.')])),
                ('birth_place', models.CharField(help_text='Enter city of birth only.', max_length=20)),
                ('birth_date', models.DateField()),
                ('occupation', models.CharField(help_text='Enter occupation here.', max_length=40)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('citizenship', models.ForeignKey(help_text='Choose citizenship.', null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.Citizenship')),
                ('civil_status', models.ForeignKey(help_text='Choose civil status.', null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.CivilStatus')),
                ('gender', models.ForeignKey(help_text='Choose gender.', null=True, on_delete=django.db.models.deletion.PROTECT, to='forms.Gender')),
                ('household_no', models.ForeignKey(help_text='Choose household where person belong to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.Household')),
                ('name_extension', models.ForeignKey(blank=True, default=5, help_text='Choose name extension, if needed.', on_delete=django.db.models.deletion.PROTECT, to='forms.NameExtension')),
            ],
        ),
    ]
