# Generated by Django 3.0.4 on 2020-11-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='occupation',
            field=models.CharField(help_text='Enter occupation here.', max_length=100),
        ),
    ]
