# Generated by Django 3.0.4 on 2020-03-14 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='household_no',
            field=models.CharField(help_text='Enter household number here.', max_length=10, validators=[django.core.validators.RegexValidator('^[0-99999]*$', message='Only numbers are allowed.')]),
        ),
    ]
