# Generated by Django 3.0.4 on 2020-11-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20201111_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='name',
            field=models.CharField(help_text='Enter a name for the household.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(help_text='Enter first name here.', max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(help_text='Enter surname here.', max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Enter middle name here, if needed.', max_length=64),
        ),
    ]
