# Generated by Django 3.0.4 on 2020-03-22 05:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20200314_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Enter middle name here.', max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z Ññ]*$', message='Only letters are allowed.')]),
        ),
    ]
