# Generated by Django 3.0.4 on 2020-10-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20201025_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='household_no',
            field=models.SmallIntegerField(help_text='Enter household number here.'),
        ),
    ]
