# Generated by Django 3.0.4 on 2020-03-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20200322_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(help_text='Enter house no. and street no.', max_length=100),
        ),
    ]
