# Generated by Django 3.0.4 on 2020-10-25 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20201025_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='citizenship',
            field=models.CharField(choices=[('FILIPINO', 'Filipino'), ('FOREIGNER', 'Foreigner')], help_text='Choose citizenship.', max_length=9),
        ),
        migrations.AlterField(
            model_name='person',
            name='civil_status',
            field=models.CharField(choices=[('MARRIED', 'Married'), ('SINGLE', 'Single'), ('SEPARATED', 'Separated'), ('WIDOWED', 'Widowed')], help_text='Choose civil status.', max_length=9),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(help_text='Enter first name here.', max_length=128, validators=[django.core.validators.RegexValidator('^[a-zA-Z Ññ]*$', message='Only letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=240, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z Ññ]*$', message='Only letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Male')], help_text='Choose gender.', max_length=6),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(help_text='Enter surname here.', max_length=128, validators=[django.core.validators.RegexValidator('^[a-zA-Z Ññ]*$', message='Only letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Enter middle name here.', max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z Ññ]*$', message='Only letters are allowed.')]),
        ),
    ]
