# Generated by Django 3.0.4 on 2020-10-29 11:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0005_auto_20201025_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(max_length=240, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z Ññ ,]*$', message='Only letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], help_text='Choose gender.', max_length=6),
        ),
    ]
