# Generated by Django 3.0.4 on 2020-10-30 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0006_auto_20201029_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='CivilStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_status', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='NameExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_extension', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='citizenship',
            field=models.ForeignKey(choices=[('FILIPINO', 'Filipino'), ('FOREIGNER', 'Foreigner')], help_text='Choose citizenship.', on_delete=django.db.models.deletion.PROTECT, to='forms.Citizenship'),
        ),
        migrations.AlterField(
            model_name='person',
            name='civil_status',
            field=models.ForeignKey(choices=[('MARRIED', 'Married'), ('SINGLE', 'Single'), ('SEPARATED', 'Separated'), ('WIDOWED', 'Widowed')], help_text='Choose civil status.', on_delete=django.db.models.deletion.PROTECT, to='forms.CivilStatus'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.ForeignKey(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], help_text='Choose gender.', on_delete=django.db.models.deletion.PROTECT, to='forms.Gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_extension',
            field=models.ForeignKey(blank=True, help_text='Choose name extension, if required.', max_length=4, on_delete=django.db.models.deletion.PROTECT, to='forms.NameExtension'),
        ),
    ]
