# Generated by Django 3.0.4 on 2020-10-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_auto_20201030_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizenship',
            name='id',
        ),
        migrations.RemoveField(
            model_name='civilstatus',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gender',
            name='id',
        ),
        migrations.RemoveField(
            model_name='nameextension',
            name='id',
        ),
        migrations.AlterField(
            model_name='citizenship',
            name='citizenship',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='civilstatus',
            name='civil_status',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nameextension',
            name='name_extension',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
