# Generated by Django 3.0.4 on 2020-10-30 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_auto_20201030_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='citizenship',
            field=models.ForeignKey(choices=[('FILIPINO', 'Filipino'), ('FOREIGNER', 'Foreigner')], db_column='citizenship', help_text='Choose citizenship.', on_delete=django.db.models.deletion.PROTECT, to='forms.Citizenship'),
        ),
        migrations.AlterField(
            model_name='person',
            name='civil_status',
            field=models.ForeignKey(choices=[('MARRIED', 'Married'), ('SINGLE', 'Single'), ('SEPARATED', 'Separated'), ('WIDOWED', 'Widowed')], db_column='civil_status', help_text='Choose civil status.', on_delete=django.db.models.deletion.PROTECT, to='forms.CivilStatus'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.ForeignKey(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], db_column='gender', help_text='Choose gender.', on_delete=django.db.models.deletion.PROTECT, to='forms.Gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name_extension',
            field=models.ForeignKey(blank=True, db_column='name_extension', help_text='Choose name extension, if required.', max_length=4, on_delete=django.db.models.deletion.PROTECT, to='forms.NameExtension'),
        ),
    ]
